### ISSUE TITLE
tslint error when using @Use at class level - An argument for 'propertyKey' was not provided

### ISSUE THREAD

**Issue by dahool** [natnathou/decorators-express#14]
When using the decorator at class level to define a middleware, I get the following error.

    @Controller("/api")
    @Use(TokenValidationMiddleware)
    export class ApiController {
    }
    
    function TokenValidationMiddleware(req: Request, res: Response, next: NextFunction) {}

The code works once compiled, but it would be nice if it didn't give any lint error.

This is with Typescript btw, and it doesn't give any error when defined at method level

**Comment by natnathou** [comment]
@dahool could you share your code in a github repo?

**Comment by dahool** [comment]
@natnathou here https://github.com/dahool/express-decorator-test

btw, when I said it works once compiled, I was wrong. The middleware never gets registered

**Comment by natnathou** [comment]
@dahool upgrade to version 1.1.15 , it should be fixed
